# Generated by Django 4.2 on 2025-10-01 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('mood', models.CharField(blank=True, choices=[('joyeux', '😊 Joyeux'), ('triste', '😢 Triste'), ('neutre', '😐 Neutre'), ('anxieux', '😰 Anxieux'), ('excite', '🤩 Excité'), ('calme', '😌 Calme'), ('colere', '😠 En colère')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('famille', 'Famille'), ('travail', 'Travail'), ('voyage', 'Voyage'), ('sante', 'Santé'), ('amour', 'Amour'), ('loisirs', 'Loisirs'), ('reflexion', 'Réflexion'), ('autre', 'Autre')], max_length=20)),
                ('auto_tags', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='core.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='core_note_created_5eb837_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-created_at'], name='core_note_user_id_19c1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['category'], name='core_note_categor_716e15_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['mood'], name='core_note_mood_cb5d62_idx'),
        ),
    ]
