# Generated by Django 5.2.7 on 2025-10-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes_images/', verbose_name='Image'),
        ),
    ]
