# Generated by Django 5.2.7 on 2025-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='notes_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
