# Generated by Django 4.2.25 on 2025-10-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this note represents a completed task/action'),
        ),
    ]
