# Generated by Django 5.2.7 on 2025-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume_notes_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='audio_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
