# Generated by Django 5.2.7 on 2025-10-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resume_audio_b64'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
