# Generated by Django 5.2.7 on 2025-10-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resume_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: famille, travail, santé...', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='period',
            field=models.CharField(blank=True, choices=[('week', 'Cette semaine'), ('month', 'Ce mois'), ('year', 'Cette année')], max_length=20, null=True),
        ),
    ]
