# Generated by Django 5.2.7 on 2025-10-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resume_category_resume_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='period',
        ),
    ]
