# Generated by Django 4.2 on 2025-10-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reminder'),
        ('core', '0007_remove_resume_category_remove_resume_period'),
    ]

    operations = [
    ]
