# Generated by Django 4.2 on 2025-10-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20251029_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
