# Generated by Django 4.2.25 on 2025-10-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_photoalbum_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
