# Generated by Django 4.2 on 2025-10-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resume_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['is_read', '-priority', '-trigger_at']},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='is_read',
        ),
        migrations.AddField(
            model_name='note',
            name='auto_title_generated',
            field=models.BooleanField(default=False, verbose_name='Titre généré automatiquement par IA'),
        ),
    ]
