# Generated by Django 4.2 on 2025-10-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20251029_1932'),
        ('core', '0010_alter_reminder_options_remove_resume_is_read_and_more'),
    ]

    operations = [
    ]
