# Generated by Django 4.2 on 2025-10-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251030_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='smart_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
