# Generated by Django 4.2.25 on 2025-10-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_photo_embedding'),
        ('core', '0012_note_smart_advice'),
    ]

    operations = [
    ]
