# Generated by Django 4.2.25 on 2025-10-01 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(help_text='Audio file of the voice recording', upload_to='voice_journal/audio/')),
                ('transcription', models.TextField(blank=True, help_text='AI-generated transcription of the audio')),
                ('text_sentiment', models.CharField(blank=True, help_text='Sentiment analysis result (POSITIVE, NEGATIVE, NEUTRAL)', max_length=20)),
                ('text_sentiment_score', models.FloatField(default=0.0, help_text='Confidence score for sentiment analysis')),
                ('audio_emotion', models.CharField(blank=True, help_text='Detected emotion from audio (calm, excited, angry, sad, neutral)', max_length=20)),
                ('audio_emotion_score', models.FloatField(default=0.0, help_text='Confidence score for emotion detection')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the voice entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the voice entry was last updated')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether this entry is marked as favorite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Journal Entry',
                'verbose_name_plural': 'Voice Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
